spring.application.name=sunrise-dental-system

spring.datasource.url=jdbc:mysql://localhost:3306/sunrise_dental
spring.datasource.username=root
spring.datasource.password=SunriseDental@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080

#log in credentials
spring.security.user.name=admin
spring.security.user.password=${APP_PASSWORD}
spring.security.user.roles=ADMIN
